### ISSUE TITLE
Runtime Error:  ExpressionChangedAfterItHasBeenCheckedError

### ISSUE THREAD

**Issue by joshuarussell10** [omnedia/ngx-swapy#1]
Hi,

I am trying to implement ngx-swapy but seem to be getting the below error.

ERROR RuntimeError: NG0100: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'undefined'. Current value: 'om-swapy-section om-swapy-section-0'. Expression location: _NgxSwapyComponent component It seems like the view has been created after its parent and its children have been dirty checked. Has it been created in a change detection hook?

"swapy": "^0.1.2",
"@omnedia/ngx-swapy": "^1.0.2",
"@angular/common": "^18.2.3"

Thanks for any feedback!

**Comment by xSentry** [comment]
I'll look into it. Does the library still run on your end tho?
Because this error shouldnt limit / stop the use of the library.

**Comment by joshuarussell10** [comment]
Yes, the feature works.

**Comment by xSentry** [comment]
With Version 1.0.3 the error doesnt occur anymore: [Commit](https://github.com/omnedia/ngx-swapy/commit/29518b97685b71be260a48492b6076e7b2aba7d8)
